survey/app/urls.py
from django.urls import path
from .views import show_surveys, show_question


app_name = 'surveys'
urlpatterns = [
    path('surveys/', show_surveys, name='surveys'),
    path('survey/<int:survey_id>/show_question/<int:question_id>', show_question, name='show_question'),
    path('survey/<int:survey_id>/show_question/', show_question, name='show_first_question'),
]

survey/survey/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

survey/users/urls.py
from django.contrib.auth.views import (
    LogoutView,
    LoginView)

from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

survey/app/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Survey(models.Model):
    """Модель опроса"""
    title = models.CharField(
        max_length=200
    )

    def __str__(self) -> str:
        return self.title


class Question(models.Model):
    """Модель вопроса"""
    survey = models.ForeignKey(
        Survey,
        on_delete=models.CASCADE
    )
    text = models.TextField()

    def __str__(self) -> str:
        return self.text


class Choice(models.Model):
    """Модель варианта ответа"""
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        related_name='choices'
    )
    text = models.CharField(
        max_length=200
    )

    def __str__(self) -> str:
        return self.text


class NextQuestionLogic(models.Model):
    """Модель для формирования логики показа следующего вопроса"""
    prev_question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        related_name='prev_question'
    )
    choice_to_the_prev_question = models.ForeignKey(
        Choice,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    next_question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='next_question'
    )
    default_next_question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='default_next_question'
    )


class SurveyResults(models.Model):
    """Модель результата опроса"""
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    survey = models.ForeignKey(
        Survey,
        on_delete=models.CASCADE
    )
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE
    )
    choice = models.ForeignKey(
        Choice,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    class Meta:
        unique_together = ('user', 'survey', 'question')

survey/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):

        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

survey/app/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required

from .models import Survey, Question, Choice, SurveyResults
from .utils import get_next_question


def show_surveys(request):
    """Страница со списком опросов"""
    surveys = Survey.objects.all()
    return render(request, 'surveys/surveys.html', {'surveys': surveys})

@login_required
def show_question(request, survey_id: int, question_id: int | None = None):
    """
    Страница с вопросом.
    При GET запросе выводим вопрос.
    При POST запросе сохраняем ответ, отрисовываем следующий вопрос.
    """
    survey = get_object_or_404(Survey, pk=survey_id)
    if question_id:
        question = Question.objects.filter(pk=question_id).first()
    else:
        question = Question.objects.filter(survey=survey).first()

    if request.method == 'POST':
        choice = None
        if 'choice' in request.POST:
            choice = get_object_or_404(Choice, pk=request.POST['choice'])
            result, _ = SurveyResults.objects.get_or_create(
                user=request.user, survey=survey, question=question
            )
            result.choice = choice
            result.save()

        next_question = get_next_question(question, choice)
        if next_question:
            return render(request, 'surveys/show_question.html',
                           {'survey': survey, 'question': next_question}
            )
        else:
            return show_results(request, survey_id)

    return render(request, 'surveys/show_question.html',
                   {'survey': survey, 'question': question}
    )


def show_results(request, survey_id: int):
    """
    Выводим статистику по опросу.
    """
    count_users = SurveyResults.objects.raw(
        '''
        SELECT 1 as id, COUNT(DISTINCT user_id) as count_users FROM app_surveyresults
        WHERE survey_id = %s
        ''',
        [survey_id]
    )[0].count_users

    questions = Survey.objects.raw(
        '''
        SELECT
            app_question.id,
            DENSE_RANK() OVER (ORDER BY COUNT(DISTINCT app_surveyresults.user_id) DESC) row_rank,
            app_question.text,
            COUNT(DISTINCT app_surveyresults.user_id) as count_users
        FROM app_question
        LEFT JOIN app_surveyresults
        ON app_question.id = app_surveyresults.question_id
        WHERE app_question.survey_id = %(survey_id)s
        GROUP BY app_question.id
        ''',
        {'survey_id': survey_id, 'count_users': count_users}
    )

    choices = Choice.objects.raw(
        '''
        SELECT
            app_question.id as question_id,
            app_choice.id,
            app_choice.text,
            COUNT(DISTINCT app_surveyresults.user_id) as count_users
        FROM app_choice
        LEFT JOIN app_question
        ON app_choice.question_id = app_question.id
        LEFT JOIN app_surveyresults
        ON app_choice.id = app_surveyresults.choice_id
        WHERE app_question.survey_id = %(survey_id)s
        GROUP BY app_question.id, app_choice.id
        ''',
        {'survey_id': survey_id}
    )

    return render(request, 'surveys/thanks.html',
                  {'cnt': count_users, 'questions': questions, 'choices': choices}
    )

survey/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('surveys:surveys')
    template_name = 'users/signup.html'

survey/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% comment %} <link rel="stylesheet" href="{% static 'css/style.css' %}"> {% endcomment %}
    <title>{% block title %}Тесты{% endblock %}</title>
  </head>
  <body>
    {% include 'includes/header.html' %}
    <main>
      {% block content %}Контент не подвезли :((({% endblock %}
    </main>
  </body>
</html>

survey/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <div class="container">
      <a class="navbar-brand" href="{% url 'surveys:surveys' %}">Тесты</a>
       <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        {% with request.resolver_match.view_name as view_name %}
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <form action="{% url 'users:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit">Выйти</button>
          </form>
        </li>
        <li class="nav-item">
          <a class="nav-link">
            Пользователь: {{ user.username }}
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link
          {% if view_name  == 'users:login' %}
            active
          {% endif %}"
          href="{% url 'users:login' %}"
          >
            Войти
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link
          {% if view_name  == 'users:signup' %}
            active
          {% endif %}"
          href="{% url 'users:signup' %}"
          >
            Регистрация
          </a>
        </li>
        {% endif %}
        {% endwith %}
      </ul>
    </div>
  </nav>
</header>

survey/templates/surveys/show_question.html
{% extends 'base.html'%}
{% block content %}
<h1>{{ question.text }}
<form action="{% url 'surveys:show_question' survey.id question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choices.all %}
        <br>
        <label for="choice" >{{ choice.text }}</label><br>
        <input type="radio" id="choice" value="{{ choice.id }}" name="choice"><br>
    {% endfor %}
    <input type="submit" value="Отправить">
</form>
{% endblock %}

survey/templates/surveys/surveys.html
{% extends 'base.html'%}
{% block content %}
<h1>Список доступных опросов</h1>
<ul>
    {% for survey in surveys %}
        <li><a href="{% url 'surveys:show_first_question' survey.id %}">{{ survey.title }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

survey/templates/surveys/thanks.html
{% extends 'base.html'%}
{% load my_custom_filters %}
{% block content %}
<h1>Результат</h1>
<h2>Общее количество участников опроса: {{ cnt }}</h2>
<h2>Вопросы: </h2>
<div class="container">
    <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Текст вопроса</th>
            <th scope="col">Кол-во ответивших</th>
            <th scope="col">% от общего кол-ва участников опроса</th>
          </tr>
        </thead>
        <tbody>
          {% for question in questions %}
          <tr>
            <th scope="row">{{ question.row_rank }}</th>
            <td><strong>{{ question.text }}</strong></td>
            <td><strong>{{ question.count_users }}</strong></td>
            <td><strong>{{ question.count_users|divide:cnt|multiply:100|floatformat }}</strong></td>
          </tr>
          <tr>

            <td colspan="4"> Варианты ответа </td>

            {% for choice in choices %}
            <tr>
            {% if choice.question_id == question.id %}
                <td></td>
                <td>
                    {{ choice.text }}
                </td>
                <td>
                    {{ choice.count_users }}
                </td>
                <td>
                    {{ choice.count_users|divide:question.count_users|multiply:100|floatformat }}
                </td>
            {% endif %}
            </tr>
            {% endfor %}
          </tr>
          {% endfor %}
        </tbody>
    </table>
  </div>
{% endblock %}

survey/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div>
    </div>
    <a href="{% url 'surveys:surveys' %}">Вернуться на главную</a>
  </div>
</div>

{% endblock %}

survey/templates/users/login.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}Войти{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-sm-4 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %}
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-sm-4 offset-md-5">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
          </div>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

survey/templates/users/signup.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-sm-6 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">

              {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}


              {% for field in form %}
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-5">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
  </div>
{% endblock %}